### ISSUE TITLE
Transition functions iteration

### ISSUE THREAD

**Issue by ColVic** [vinyasns/dfa-to-regex#1]
```py
print('Define the transition function : ')
transition_matrix = [list(map(str, input().split())) for _ in range(len(states))]
transition_funct = dict(zip(states, transition_matrix))
```
The array consists of `len(states)` elements, what if number of states differs from number of transitions?
```
DFA:
Q = {q0, [q1, q2], [q1, q3], q2, q1, q3}
Σ = {a, b}
I = q0
F = {[q1, q3], q3}
𝛿(q0, a) = [q1, q2]
𝛿([q1, q2], a) = [q1, q2]
𝛿([q1, q2], b) = [q1, q3]
𝛿([q1, q3], a) = q2
𝛿([q1, q3], b) = q1
𝛿(q2, a) = q1
𝛿(q2, b) = q3
𝛿(q1, a) = q2
𝛿(q1, b) = q1
```
Can you provide please and example of input for transition functions?

p.s. I like your code, it helped me with the same task.

**Comment by vinyasns** [comment]
As of now, this code handles only single final state.
Handling multiple final states will be done in future.

**Comment by vinyasns** [comment]
Transition function is taken as input as below:
Example :
```
q1 q1
q1 q2
q2 q2
```

which defines transition function as : 

```
   | a   |  b  |
---------------------
q0 |  q1 | q1
q1 |  q1 | q2
q2 |  q2 | q2
```

means,

(q0, a) -> q1
(q0, b) -> q1
(q2, a) -> q2

and so on..

**Comment by vinyasns** [comment]
And in DFA you should define transition function to every states for every input symbol. Otherwise, it'll be NFA not DFA!
